modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="minedivers"
version="${file.jarVersion}"
displayName="MineDivers"
description='''
A Minecraft mod for server enhancements.
'''
authors="YourName"

[[dependencies.minedivers]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.minedivers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"